# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - iiwa7_arm_controller

  iiwa7_arm_controller:
    type: FollowJointTrajectory
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    action_ns: follow_joint_trajectory
    default: true